from .lang.lambda_dcs.lambda_dcs_transition_system import LambdaCalculusTransitionSystem
from .lang.prolog.prolog_transition_system import PrologTransitionSystem
from .lang.java.java_transition_system import JavaTransitionSystem
from .lang.py3.py3_transition_system import Python3TransitionSystem

